### ISSUE TITLE
Core.SetGroupMembership block: Allow set multiple groups at once

### ISSUE THREAD

**Issue by jcbalmeida** [FLOIP/flow-spec#62]
In some cases it would be interesting to be able to add or remove a contact from more than one group in the same block. For example:

```
{
  "type": "Core.SetGroupMembership",
  "name": "AddToMultipleGroups",
  "label": "Add to multiple groups",
  "config": {
    "groups": [
      {
        "group_key": "59c2ef5d-aeff-4df3-b717-f0624f96db74",
        "group_name": "Survey Audience"
      },
      {
        "group_key": "2d5a6b73-c1d1-448d-99d6-8942dd8e4935",
        "group_name": "Unsatisfied Customers"
      }
    ],
    "is_member": true
  },
  "exits": [
    {
      "uuid": "6827500a-38b7-4dc3-803c-d2c14e961a0f",
      "name": "Default",
      "default": true
    }
  ]
}
```
It is even a very common case in some RapidPro flows, where a certain condition (sometimes simply the beginning of the flow) justifies categorizing the contact in more than one group.

It is perfectly possible to do the same thing by creating a block for each group, but this ends up making the flow more extensive to perform the same action N times. Does it make any sense or is it not worth the increase in block complexity?

**Comment by markboots** [comment]
Hi @jcbalmeida , thanks for the suggestion!  I'd be in favour of this change for the benefits of:

- Simplifying the RapidPro -> Flow Interop conversion for this action/block.
- It keeps the structure of flows simpler when there is a need to add to multiple groups.  As a general principle, Flows have a tendency to get big/complex in terms of the number of blocks already... Increasing the configuration in a way that allows reducing the number of blocks required is often helpful.
- From Viamo's perspective, we've heard from power users that the ability to set multiple group memberships at once would be nice to have.  (It's obviously not required, as you can achieve the same with multiple blocks.)

**Comment by smn** [comment]
I'm in favour of this, and while we're at it, are we open to doing the same for Core.SetContactProperty? Right now that only allows updating a single value and requires multiple blocks for multiple properties which gets cumbersome in similar ways as described here for Core.SetGroupMembership

**Comment by markboots** [comment]
Thanks @smn!  Appreciate the parallel connection to Core.SetContactProperty.  For that one, even though it could be nice to treat these the same, I have a small preference for leaving it as a single contact property:
- In terms of aiding RapidPro convertibility into Flow standard:  The corresponding RapidPro action is a single property (unlike SetGroupMembership), so the current definition matches up easily.
- (Internal Viamo preference - not necessarily community-wide):  Making this change to our existing implementation would be a heavier lift.
- The UI to configure multiple SetContactProperties would be more complex than for the SetGroupMembership, because there are keys and values for each, along with type verification.    On the group side, we just need a multi-select of groups, which has lots of good standard UIs.

If we look ahead to what users need, is there a strong preference for multiple properties in SetContactProperty?

**Comment by markboots** [comment]
In the community meeting on July 4, there was a strong recommendation to support multiple properties in the SetContactProperty block as well. Setting multiple properties in one go is an active use-case used by Turn and RapidPro flows; it would do a lot to create simpler, more interoperable flows vs. the workaround of many individual blocks.   We can include this change to Core.SetContactProperty in the scope of this issue as well.

Since other partners don't use the block.set_contact_property field, we would recommend maintaining this as-is.
